#!/bin/bash

exec 2>&1

# Move directories that ship in the package into place
cp -a $(hab pkg path core/tomcat8)/tc {{pkg.svc_var_path}}/

# Symlink config files into $TOMCAT_HOME/conf
for file in $(cd {{pkg.svc_config_path}}; ls -1)
do
  echo "Linking $file"
  target="${file//_//}"
  ln -vsf {{pkg.svc_config_path}}/$file {{pkg.svc_var_path}}/tc/$target
done

echo "Done preparing TOMCAT_HOME"

echo "Seeding Mongo Collection"

source {{pkg.svc_config_path}}/mongoimport-opts.conf
echo "\$MONGOIMPORT_OPTS=$MONGOIMPORT_OPTS"

echo "sys.ip        = {{sys.ip}}"
echo "sys.hostname  = {{sys.hostname}}"
echo "pkg.origin    = {{pkg.origin}}"
echo "pkg.name      = {{pkg.name}}"
echo "pkg.version   = {{pkg.version}}"
echo "pkg.release   = {{pkg.release}}"
echo "pkg.ident     = {{pkg.ident}}"
echo "pkg.deps      = {{pkg.deps}}"
echo "pkg.exposes   = {{pkg.exposes}}"
echo "pkg.svc_path          = {{pkg.svc_path}}"
echo "pkg.svc_config_path   = {{pkg.svc_config_path}}"
echo "pkg.svc_data_path     = {{pkg.svc_data_path}}"
echo "pkg.svc_files_path    = {{pkg.svc_files_path}}"
echo "pkg.svc_static_path   = {{pkg.svc_static_path}}"
echo "pkg.svc_var_path      = {{pkg.svc_var_path}}"

echo mongoimport --drop -d demo -c nationalparks --type json --jsonArray --file /hab/pkgs/{{pkg.ident}}/national-parks.json ${MONGOIMPORT_OPTS}
mongoimport --drop -d demo -c nationalparks --type json --jsonArray --file /hab/pkgs/{{pkg.ident}}/national-parks.json ${MONGOIMPORT_OPTS}
